// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.11.1.

// ignore_for_file: invalid_use_of_internal_member, unused_import, unnecessary_import

import 'frb_generated.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';
import 'package:freezed_annotation/freezed_annotation.dart' hide protected;
part 'lib.freezed.dart';

Future<GeographicCoordinate> passthroughCoordinate({
  required GeographicCoordinate coord,
}) => RustLib.instance.api.cratePassthroughCoordinate(coord: coord);

/// Helper to build a `GeographicCoordinate` from primitives (Dart cannot construct opaque types directly).
Future<GeographicCoordinate> makeGeographicCoordinate({
  required double lat,
  required double lng,
}) => RustLib.instance.api.crateMakeGeographicCoordinate(lat: lat, lng: lng);

/// Parses an OSRM/Valhalla response into routes using the core parser.
Future<List<Route>> parseOsrmResponse({
  required List<int> response,
  required int polylinePrecision,
}) => RustLib.instance.api.crateParseOsrmResponse(
  response: response,
  polylinePrecision: polylinePrecision,
);

/// Convenience helper to build a waypoint with Valhalla rich properties.
Future<Waypoint> createWaypointWithValhallaProperties({
  required GeographicCoordinate coordinate,
  required WaypointKind kind,
  required ValhallaWaypointProperties properties,
}) => RustLib.instance.api.crateCreateWaypointWithValhallaProperties(
  coordinate: coordinate,
  kind: kind,
  properties: properties,
);

/// Create default Valhalla waypoint properties (workaround for Dart-side opaque type construction).
Future<ValhallaWaypointProperties> defaultValhallaWaypointProperties() =>
    RustLib.instance.api.crateDefaultValhallaWaypointProperties();

/// Convenience accessor for the common Break waypoint kind.
Future<WaypointKind> waypointKindBreak() =>
    RustLib.instance.api.crateWaypointKindBreak();

/// Sync helper to create a user location (keeps Flutter API compatibility).
UserLocation createUserLocation({
  required GeographicCoordinate coordinates,
  required double horizontalAccuracy,
  CourseOverGround? courseOverGround,
  required DateTime timestamp,
  Speed? speed,
}) => RustLib.instance.api.crateCreateUserLocation(
  coordinates: coordinates,
  horizontalAccuracy: horizontalAccuracy,
  courseOverGround: courseOverGround,
  timestamp: timestamp,
  speed: speed,
);

/// Extract route geometry into simple coordinates for Dart consumption.
Future<List<SimpleGeographicCoordinate>> routeGeometry({
  required Route route,
}) => RustLib.instance.api.crateRouteGeometry(route: route);

/// Generate a Valhalla request and return a Dart-friendly shape.
Future<FerrostarRouteRequest> generateValhallaRequest({
  required String endpointUrl,
  required String profile,
  required UserLocation userLocation,
  required List<Waypoint> waypoints,
}) => RustLib.instance.api.crateGenerateValhallaRequest(
  endpointUrl: endpointUrl,
  profile: profile,
  userLocation: userLocation,
  waypoints: waypoints,
);

// Rust type: RustOpaqueMoi<flutter_rust_bridge::for_generated::RustAutoOpaqueInner<CourseOverGround>>
abstract class CourseOverGround implements RustOpaqueInterface {}

// Rust type: RustOpaqueMoi<flutter_rust_bridge::for_generated::RustAutoOpaqueInner<FlutterNavState>>
abstract class FlutterNavState implements RustOpaqueInterface {
  Future<TripState> tripState();
}

// Rust type: RustOpaqueMoi<flutter_rust_bridge::for_generated::RustAutoOpaqueInner<FlutterNavigationController>>
abstract class FlutterNavigationController implements RustOpaqueInterface {
  Future<FlutterNavState> advanceToNextStep({required FlutterNavState state});

  Future<FlutterNavState> getInitialState({required UserLocation location});

  // HINT: Make it `#[frb(sync)]` to let it become the default constructor of Dart class.
  static Future<FlutterNavigationController> newInstance({
    required Route route,
    required NavigationControllerConfig config,
  }) => RustLib.instance.api.crateFlutterNavigationControllerNew(
    route: route,
    config: config,
  );

  Future<FlutterNavState> updateUserLocation({
    required UserLocation location,
    required FlutterNavState state,
  });
}

// Rust type: RustOpaqueMoi<flutter_rust_bridge::for_generated::RustAutoOpaqueInner<GeographicCoordinate>>
abstract class GeographicCoordinate implements RustOpaqueInterface {}

// Rust type: RustOpaqueMoi<flutter_rust_bridge::for_generated::RustAutoOpaqueInner<NavigationControllerConfig>>
abstract class NavigationControllerConfig implements RustOpaqueInterface {}

// Rust type: RustOpaqueMoi<flutter_rust_bridge::for_generated::RustAutoOpaqueInner<Route>>
abstract class Route implements RustOpaqueInterface {}

// Rust type: RustOpaqueMoi<flutter_rust_bridge::for_generated::RustAutoOpaqueInner<RouteRequest>>
abstract class RouteRequest implements RustOpaqueInterface {}

// Rust type: RustOpaqueMoi<flutter_rust_bridge::for_generated::RustAutoOpaqueInner<Speed>>
abstract class Speed implements RustOpaqueInterface {}

// Rust type: RustOpaqueMoi<flutter_rust_bridge::for_generated::RustAutoOpaqueInner<TripState>>
abstract class TripState implements RustOpaqueInterface {}

// Rust type: RustOpaqueMoi<flutter_rust_bridge::for_generated::RustAutoOpaqueInner<UserLocation>>
abstract class UserLocation implements RustOpaqueInterface {}

// Rust type: RustOpaqueMoi<flutter_rust_bridge::for_generated::RustAutoOpaqueInner<ValhallaHttpRequestGenerator>>
abstract class ValhallaHttpRequestGenerator implements RustOpaqueInterface {
  Future<RouteRequest> generateRequest({
    required UserLocation userLocation,
    required List<Waypoint> waypoints,
  });

  /// Creates a Valhalla request generator with no additional options.
  factory ValhallaHttpRequestGenerator({
    required String endpointUrl,
    required String profile,
  }) => RustLib.instance.api.crateValhallaHttpRequestGeneratorNew(
    endpointUrl: endpointUrl,
    profile: profile,
  );
}

// Rust type: RustOpaqueMoi<flutter_rust_bridge::for_generated::RustAutoOpaqueInner<ValhallaWaypointProperties>>
abstract class ValhallaWaypointProperties implements RustOpaqueInterface {}

// Rust type: RustOpaqueMoi<flutter_rust_bridge::for_generated::RustAutoOpaqueInner<Waypoint>>
abstract class Waypoint implements RustOpaqueInterface {}

// Rust type: RustOpaqueMoi<flutter_rust_bridge::for_generated::RustAutoOpaqueInner<WaypointKind>>
abstract class WaypointKind implements RustOpaqueInterface {}

@freezed
sealed class FerrostarRouteRequest with _$FerrostarRouteRequest {
  const FerrostarRouteRequest._();

  const factory FerrostarRouteRequest.httpGet({
    required String url,
    required List<(String, String)> headers,
  }) = FerrostarRouteRequest_HttpGet;
  const factory FerrostarRouteRequest.httpPost({
    required String url,
    required List<(String, String)> headers,
    required Uint8List body,
  }) = FerrostarRouteRequest_HttpPost;
}

/// Simple coordinate DTO to allow Dart to read lat/lng.
class SimpleGeographicCoordinate {
  final double lat;
  final double lng;

  const SimpleGeographicCoordinate({required this.lat, required this.lng});

  @override
  int get hashCode => lat.hashCode ^ lng.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is SimpleGeographicCoordinate &&
          runtimeType == other.runtimeType &&
          lat == other.lat &&
          lng == other.lng;
}
