// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.11.1.

// ignore_for_file: invalid_use_of_internal_member, unused_import, unnecessary_import

import '../frb_generated.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';
import 'package:freezed_annotation/freezed_annotation.dart' hide protected;
import 'package:uuid/uuid.dart';
part 'models.freezed.dart';

// These function are ignored because they are on traits that is not defined in current crate (put an empty `#[frb]` on it to unignore): `from`, `from`, `from`, `from`, `from`

enum BlockedLane {
  left,
  leftCenter,
  leftTurnLane,
  center,
  right,
  rightCenter,
  rightTurnLane,
  hov,
}

class BoundingBox {
  final GeographicCoordinate sw;
  final GeographicCoordinate ne;

  const BoundingBox({required this.sw, required this.ne});

  @override
  int get hashCode => sw.hashCode ^ ne.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is BoundingBox &&
          runtimeType == other.runtimeType &&
          sw == other.sw &&
          ne == other.ne;
}

class Congestion {
  final int value;

  const Congestion({required this.value});

  @override
  int get hashCode => value.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is Congestion &&
          runtimeType == other.runtimeType &&
          value == other.value;
}

enum CourseFiltering { snapToRoute, raw }

class CourseOverGround {
  final int degrees;
  final int? accuracy;

  const CourseOverGround({required this.degrees, this.accuracy});

  @override
  int get hashCode => degrees.hashCode ^ accuracy.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is CourseOverGround &&
          runtimeType == other.runtimeType &&
          degrees == other.degrees &&
          accuracy == other.accuracy;
}

class FlutterNavigationControllerConfig {
  final WaypointAdvanceMode waypointAdvance;
  final SerializableStepAdvanceCondition stepAdvanceCondition;
  final SerializableStepAdvanceCondition arrivalStepAdvanceCondition;
  final FlutterRouteDeviationTracking routeDeviationTracking;
  final CourseFiltering snappedLocationCourseFiltering;

  const FlutterNavigationControllerConfig({
    required this.waypointAdvance,
    required this.stepAdvanceCondition,
    required this.arrivalStepAdvanceCondition,
    required this.routeDeviationTracking,
    required this.snappedLocationCourseFiltering,
  });

  @override
  int get hashCode =>
      waypointAdvance.hashCode ^
      stepAdvanceCondition.hashCode ^
      arrivalStepAdvanceCondition.hashCode ^
      routeDeviationTracking.hashCode ^
      snappedLocationCourseFiltering.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is FlutterNavigationControllerConfig &&
          runtimeType == other.runtimeType &&
          waypointAdvance == other.waypointAdvance &&
          stepAdvanceCondition == other.stepAdvanceCondition &&
          arrivalStepAdvanceCondition == other.arrivalStepAdvanceCondition &&
          routeDeviationTracking == other.routeDeviationTracking &&
          snappedLocationCourseFiltering ==
              other.snappedLocationCourseFiltering;
}

@freezed
sealed class FlutterRouteDeviationTracking
    with _$FlutterRouteDeviationTracking {
  const FlutterRouteDeviationTracking._();

  const factory FlutterRouteDeviationTracking.none() =
      FlutterRouteDeviationTracking_None;
  const factory FlutterRouteDeviationTracking.staticThreshold({
    required int minimumHorizontalAccuracy,
    required double maxAcceptableDeviation,
  }) = FlutterRouteDeviationTracking_StaticThreshold;
}

@freezed
sealed class FlutterTripState with _$FlutterTripState {
  const FlutterTripState._();

  const factory FlutterTripState.idle({FlutterUserLocation? userLocation}) =
      FlutterTripState_Idle;
  const factory FlutterTripState.navigating({
    BigInt? currentStepGeometryIndex,
    required FlutterUserLocation userLocation,
    required FlutterUserLocation snappedUserLocation,
    required List<RouteStep> remainingSteps,
    required List<Waypoint> remainingWaypoints,
    required TripProgress progress,
    required TripSummary summary,
    required RouteDeviation deviation,
    VisualInstruction? visualInstruction,
    SpokenInstruction? spokenInstruction,
    String? annotationJson,
  }) = FlutterTripState_Navigating;
  const factory FlutterTripState.complete({
    required FlutterUserLocation userLocation,
    required TripSummary summary,
  }) = FlutterTripState_Complete;
}

class FlutterUserLocation {
  final GeographicCoordinate coordinates;
  final double horizontalAccuracy;
  final CourseOverGround? courseOverGround;
  final DateTime timestamp;
  final Speed? speed;

  const FlutterUserLocation({
    required this.coordinates,
    required this.horizontalAccuracy,
    this.courseOverGround,
    required this.timestamp,
    this.speed,
  });

  @override
  int get hashCode =>
      coordinates.hashCode ^
      horizontalAccuracy.hashCode ^
      courseOverGround.hashCode ^
      timestamp.hashCode ^
      speed.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is FlutterUserLocation &&
          runtimeType == other.runtimeType &&
          coordinates == other.coordinates &&
          horizontalAccuracy == other.horizontalAccuracy &&
          courseOverGround == other.courseOverGround &&
          timestamp == other.timestamp &&
          speed == other.speed;
}

class GeographicCoordinate {
  final double lat;
  final double lng;

  const GeographicCoordinate({required this.lat, required this.lng});

  @override
  int get hashCode => lat.hashCode ^ lng.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is GeographicCoordinate &&
          runtimeType == other.runtimeType &&
          lat == other.lat &&
          lng == other.lng;
}

enum Impact { unknown, critical, major, minor, low }

class Incident {
  final String id;
  final IncidentType incidentType;
  final String? description;
  final String? longDescription;
  final DateTime? creationTime;
  final DateTime? startTime;
  final DateTime? endTime;
  final Impact? impact;
  final List<BlockedLane> lanesBlocked;
  final Congestion? congestion;
  final bool? closed;
  final BigInt geometryIndexStart;
  final BigInt? geometryIndexEnd;
  final String? subType;
  final String? subTypeDescription;
  final String? iso31661Alpha2;
  final String? iso31661Alpha3;
  final List<String> affectedRoadNames;
  final BoundingBox? bbox;

  const Incident({
    required this.id,
    required this.incidentType,
    this.description,
    this.longDescription,
    this.creationTime,
    this.startTime,
    this.endTime,
    this.impact,
    required this.lanesBlocked,
    this.congestion,
    this.closed,
    required this.geometryIndexStart,
    this.geometryIndexEnd,
    this.subType,
    this.subTypeDescription,
    this.iso31661Alpha2,
    this.iso31661Alpha3,
    required this.affectedRoadNames,
    this.bbox,
  });

  @override
  int get hashCode =>
      id.hashCode ^
      incidentType.hashCode ^
      description.hashCode ^
      longDescription.hashCode ^
      creationTime.hashCode ^
      startTime.hashCode ^
      endTime.hashCode ^
      impact.hashCode ^
      lanesBlocked.hashCode ^
      congestion.hashCode ^
      closed.hashCode ^
      geometryIndexStart.hashCode ^
      geometryIndexEnd.hashCode ^
      subType.hashCode ^
      subTypeDescription.hashCode ^
      iso31661Alpha2.hashCode ^
      iso31661Alpha3.hashCode ^
      affectedRoadNames.hashCode ^
      bbox.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is Incident &&
          runtimeType == other.runtimeType &&
          id == other.id &&
          incidentType == other.incidentType &&
          description == other.description &&
          longDescription == other.longDescription &&
          creationTime == other.creationTime &&
          startTime == other.startTime &&
          endTime == other.endTime &&
          impact == other.impact &&
          lanesBlocked == other.lanesBlocked &&
          congestion == other.congestion &&
          closed == other.closed &&
          geometryIndexStart == other.geometryIndexStart &&
          geometryIndexEnd == other.geometryIndexEnd &&
          subType == other.subType &&
          subTypeDescription == other.subTypeDescription &&
          iso31661Alpha2 == other.iso31661Alpha2 &&
          iso31661Alpha3 == other.iso31661Alpha3 &&
          affectedRoadNames == other.affectedRoadNames &&
          bbox == other.bbox;
}

enum IncidentType {
  accident,
  congestion,
  construction,
  disabledVehicle,
  laneRestriction,
  massTransit,
  miscellaneous,
  otherNews,
  plannedEvent,
  roadClosure,
  roadHazard,
  weather,
}

class LaneInfo {
  final bool active;
  final List<String> directions;
  final String? activeDirection;

  const LaneInfo({
    required this.active,
    required this.directions,
    this.activeDirection,
  });

  @override
  int get hashCode =>
      active.hashCode ^ directions.hashCode ^ activeDirection.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is LaneInfo &&
          runtimeType == other.runtimeType &&
          active == other.active &&
          directions == other.directions &&
          activeDirection == other.activeDirection;
}

enum ManeuverModifier {
  uTurn,
  sharpRight,
  right,
  slightRight,
  straight,
  slightLeft,
  left,
  sharpLeft,
}

enum ManeuverType {
  turn,
  newName,
  depart,
  arrive,
  merge,
  onRamp,
  offRamp,
  fork,
  endOfRoad,
  continue_,
  roundabout,
  rotary,
  roundaboutTurn,
  notification,
  exitRoundabout,
  exitRotary,
}

class Route {
  final List<GeographicCoordinate> geometry;
  final BoundingBox bbox;
  final double distance;
  final List<Waypoint> waypoints;
  final List<RouteStep> steps;

  const Route({
    required this.geometry,
    required this.bbox,
    required this.distance,
    required this.waypoints,
    required this.steps,
  });

  @override
  int get hashCode =>
      geometry.hashCode ^
      bbox.hashCode ^
      distance.hashCode ^
      waypoints.hashCode ^
      steps.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is Route &&
          runtimeType == other.runtimeType &&
          geometry == other.geometry &&
          bbox == other.bbox &&
          distance == other.distance &&
          waypoints == other.waypoints &&
          steps == other.steps;
}

@freezed
sealed class RouteDeviation with _$RouteDeviation {
  const RouteDeviation._();

  const factory RouteDeviation.noDeviation() = RouteDeviation_NoDeviation;
  const factory RouteDeviation.offRoute({
    required double deviationFromRouteLine,
  }) = RouteDeviation_OffRoute;
}

class RouteStep {
  final List<GeographicCoordinate> geometry;
  final double distance;
  final double duration;
  final String? roadName;
  final List<String> exits;
  final String instruction;
  final List<VisualInstruction> visualInstructions;
  final List<SpokenInstruction> spokenInstructions;
  final List<String>? annotations;
  final List<Incident> incidents;

  const RouteStep({
    required this.geometry,
    required this.distance,
    required this.duration,
    this.roadName,
    required this.exits,
    required this.instruction,
    required this.visualInstructions,
    required this.spokenInstructions,
    this.annotations,
    required this.incidents,
  });

  @override
  int get hashCode =>
      geometry.hashCode ^
      distance.hashCode ^
      duration.hashCode ^
      roadName.hashCode ^
      exits.hashCode ^
      instruction.hashCode ^
      visualInstructions.hashCode ^
      spokenInstructions.hashCode ^
      annotations.hashCode ^
      incidents.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is RouteStep &&
          runtimeType == other.runtimeType &&
          geometry == other.geometry &&
          distance == other.distance &&
          duration == other.duration &&
          roadName == other.roadName &&
          exits == other.exits &&
          instruction == other.instruction &&
          visualInstructions == other.visualInstructions &&
          spokenInstructions == other.spokenInstructions &&
          annotations == other.annotations &&
          incidents == other.incidents;
}

@freezed
sealed class SerializableStepAdvanceCondition
    with _$SerializableStepAdvanceCondition {
  const SerializableStepAdvanceCondition._();

  const factory SerializableStepAdvanceCondition.manual() =
      SerializableStepAdvanceCondition_Manual;
  const factory SerializableStepAdvanceCondition.distanceToEndOfStep({
    required int distance,
    required int minimumHorizontalAccuracy,
  }) = SerializableStepAdvanceCondition_DistanceToEndOfStep;
  const factory SerializableStepAdvanceCondition.distanceFromStep({
    required int distance,
    required int minimumHorizontalAccuracy,
  }) = SerializableStepAdvanceCondition_DistanceFromStep;
  const factory SerializableStepAdvanceCondition.distanceEntryExit({
    required int distanceToEndOfStep,
    required int distanceAfterEndStep,
    required int minimumHorizontalAccuracy,
    required bool hasReachedEndOfCurrentStep,
  }) = SerializableStepAdvanceCondition_DistanceEntryExit;
  const factory SerializableStepAdvanceCondition.orAdvanceConditions({
    required List<SerializableStepAdvanceCondition> conditions,
  }) = SerializableStepAdvanceCondition_OrAdvanceConditions;
  const factory SerializableStepAdvanceCondition.andAdvanceConditions({
    required List<SerializableStepAdvanceCondition> conditions,
  }) = SerializableStepAdvanceCondition_AndAdvanceConditions;
}

class Speed {
  final double value;
  final double? accuracy;

  const Speed({required this.value, this.accuracy});

  @override
  int get hashCode => value.hashCode ^ accuracy.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is Speed &&
          runtimeType == other.runtimeType &&
          value == other.value &&
          accuracy == other.accuracy;
}

class SpokenInstruction {
  final String text;
  final String? ssml;
  final double triggerDistanceBeforeManeuver;
  final UuidValue utteranceId;

  const SpokenInstruction({
    required this.text,
    this.ssml,
    required this.triggerDistanceBeforeManeuver,
    required this.utteranceId,
  });

  @override
  int get hashCode =>
      text.hashCode ^
      ssml.hashCode ^
      triggerDistanceBeforeManeuver.hashCode ^
      utteranceId.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is SpokenInstruction &&
          runtimeType == other.runtimeType &&
          text == other.text &&
          ssml == other.ssml &&
          triggerDistanceBeforeManeuver ==
              other.triggerDistanceBeforeManeuver &&
          utteranceId == other.utteranceId;
}

class TripProgress {
  final double distanceToNextManeuver;
  final double distanceRemaining;
  final double durationRemaining;

  const TripProgress({
    required this.distanceToNextManeuver,
    required this.distanceRemaining,
    required this.durationRemaining,
  });

  @override
  int get hashCode =>
      distanceToNextManeuver.hashCode ^
      distanceRemaining.hashCode ^
      durationRemaining.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is TripProgress &&
          runtimeType == other.runtimeType &&
          distanceToNextManeuver == other.distanceToNextManeuver &&
          distanceRemaining == other.distanceRemaining &&
          durationRemaining == other.durationRemaining;
}

class TripSummary {
  final double distanceTraveled;
  final double snappedDistanceTraveled;
  final DateTime startedAt;
  final DateTime? endedAt;

  const TripSummary({
    required this.distanceTraveled,
    required this.snappedDistanceTraveled,
    required this.startedAt,
    this.endedAt,
  });

  @override
  int get hashCode =>
      distanceTraveled.hashCode ^
      snappedDistanceTraveled.hashCode ^
      startedAt.hashCode ^
      endedAt.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is TripSummary &&
          runtimeType == other.runtimeType &&
          distanceTraveled == other.distanceTraveled &&
          snappedDistanceTraveled == other.snappedDistanceTraveled &&
          startedAt == other.startedAt &&
          endedAt == other.endedAt;
}

class VisualInstruction {
  final VisualInstructionContent primaryContent;
  final VisualInstructionContent? secondaryContent;
  final VisualInstructionContent? subContent;
  final double triggerDistanceBeforeManeuver;

  const VisualInstruction({
    required this.primaryContent,
    this.secondaryContent,
    this.subContent,
    required this.triggerDistanceBeforeManeuver,
  });

  @override
  int get hashCode =>
      primaryContent.hashCode ^
      secondaryContent.hashCode ^
      subContent.hashCode ^
      triggerDistanceBeforeManeuver.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is VisualInstruction &&
          runtimeType == other.runtimeType &&
          primaryContent == other.primaryContent &&
          secondaryContent == other.secondaryContent &&
          subContent == other.subContent &&
          triggerDistanceBeforeManeuver == other.triggerDistanceBeforeManeuver;
}

class VisualInstructionContent {
  final String text;
  final ManeuverType? maneuverType;
  final ManeuverModifier? maneuverModifier;
  final int? roundaboutExitDegrees;
  final List<LaneInfo>? laneInfo;
  final List<String> exitNumbers;

  const VisualInstructionContent({
    required this.text,
    this.maneuverType,
    this.maneuverModifier,
    this.roundaboutExitDegrees,
    this.laneInfo,
    required this.exitNumbers,
  });

  @override
  int get hashCode =>
      text.hashCode ^
      maneuverType.hashCode ^
      maneuverModifier.hashCode ^
      roundaboutExitDegrees.hashCode ^
      laneInfo.hashCode ^
      exitNumbers.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is VisualInstructionContent &&
          runtimeType == other.runtimeType &&
          text == other.text &&
          maneuverType == other.maneuverType &&
          maneuverModifier == other.maneuverModifier &&
          roundaboutExitDegrees == other.roundaboutExitDegrees &&
          laneInfo == other.laneInfo &&
          exitNumbers == other.exitNumbers;
}

class Waypoint {
  final GeographicCoordinate coordinate;
  final WaypointKind kind;

  const Waypoint({required this.coordinate, required this.kind});

  @override
  int get hashCode => coordinate.hashCode ^ kind.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is Waypoint &&
          runtimeType == other.runtimeType &&
          coordinate == other.coordinate &&
          kind == other.kind;
}

@freezed
sealed class WaypointAdvanceMode with _$WaypointAdvanceMode {
  const WaypointAdvanceMode._();

  const factory WaypointAdvanceMode.waypointWithinRange(double field0) =
      WaypointAdvanceMode_WaypointWithinRange;
}

enum WaypointKind { break_, via }
