// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.11.1.

// ignore_for_file: invalid_use_of_internal_member, unused_import, unnecessary_import

import '../frb_generated.dart';
import 'models.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';
import 'package:uuid/uuid.dart';

// Rust type: RustOpaqueMoi<flutter_rust_bridge::for_generated::RustAutoOpaqueInner<FlutterNavState>>
abstract class FlutterNavState implements RustOpaqueInterface {
  Future<TripState> tripState();
}

// Rust type: RustOpaqueMoi<flutter_rust_bridge::for_generated::RustAutoOpaqueInner<FlutterNavigationController>>
abstract class FlutterNavigationController implements RustOpaqueInterface {
  Future<FlutterNavState> advanceToNextStep({required FlutterNavState state});

  Future<FlutterNavState> getInitialState({required UserLocation location});

  // HINT: Make it `#[frb(sync)]` to let it become the default constructor of Dart class.
  static Future<FlutterNavigationController> newInstance({
    required Route route,
    required NavigationControllerConfig config,
  }) => RustLib.instance.api.crateApiNavigationFlutterNavigationControllerNew(
    route: route,
    config: config,
  );

  Future<FlutterNavState> updateUserLocation({
    required UserLocation location,
    required FlutterNavState state,
  });
}
