// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.11.1.

// ignore_for_file: invalid_use_of_internal_member, unused_import, unnecessary_import

import '../frb_generated.dart';
import 'models.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';
import 'package:freezed_annotation/freezed_annotation.dart' hide protected;
import 'package:uuid/uuid.dart';
part 'routing.freezed.dart';

Future<List<Route>> parseOsrmResponse({
  required List<int> response,
  required int polylinePrecision,
}) => RustLib.instance.api.crateApiRoutingParseOsrmResponse(
  response: response,
  polylinePrecision: polylinePrecision,
);

Future<FlutterRouteRequest> getValhallaRequest({
  required String baseUrl,
  required String apiKey,
  required UserLocation userLocation,
  required List<Waypoint> waypoints,
  required String costing,
}) => RustLib.instance.api.crateApiRoutingGetValhallaRequest(
  baseUrl: baseUrl,
  apiKey: apiKey,
  userLocation: userLocation,
  waypoints: waypoints,
  costing: costing,
);

@freezed
sealed class FlutterRouteRequest with _$FlutterRouteRequest {
  const FlutterRouteRequest._();

  const factory FlutterRouteRequest.httpPost({
    required String url,
    required Map<String, String> headers,
    required Uint8List body,
  }) = FlutterRouteRequest_HttpPost;
  const factory FlutterRouteRequest.httpGet({
    required String url,
    required Map<String, String> headers,
  }) = FlutterRouteRequest_HttpGet;
}
