// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.11.1.

// ignore_for_file: invalid_use_of_internal_member, unused_import, unnecessary_import

import '../frb_generated.dart';
import 'models.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';
import 'package:freezed_annotation/freezed_annotation.dart' hide protected;
import 'package:uuid/uuid.dart';
part 'routing.freezed.dart';

Future<List<Route>> parseOsrmResponse({
  required List<int> response,
  required int polylinePrecision,
}) => RustLib.instance.api.crateApiRoutingParseOsrmResponse(
  response: response,
  polylinePrecision: polylinePrecision,
);

Future<Waypoint> createWaypointWithValhallaProperties({
  required GeographicCoordinate coordinate,
  required WaypointKind kind,
  required ValhallaWaypointProperties properties,
}) => RustLib.instance.api.crateApiRoutingCreateWaypointWithValhallaProperties(
  coordinate: coordinate,
  kind: kind,
  properties: properties,
);

// Rust type: RustOpaqueMoi<flutter_rust_bridge::for_generated::RustAutoOpaqueInner<ValhallaHttpRequestGenerator>>
abstract class ValhallaHttpRequestGenerator implements RustOpaqueInterface {
  Future<FerrostarRouteRequest> generateRequest({
    required UserLocation userLocation,
    required List<Waypoint> waypoints,
  });

  // HINT: Make it `#[frb(sync)]` to let it become the default constructor of Dart class.
  static Future<ValhallaHttpRequestGenerator> newInstance({
    required String endpointUrl,
    required String profile,
  }) => RustLib.instance.api.crateApiRoutingValhallaHttpRequestGeneratorNew(
    endpointUrl: endpointUrl,
    profile: profile,
  );
}

@freezed
sealed class FerrostarRouteRequest with _$FerrostarRouteRequest {
  const FerrostarRouteRequest._();

  const factory FerrostarRouteRequest.httpPost({
    required String url,
    required Map<String, String> headers,
    required Uint8List body,
  }) = FerrostarRouteRequest_HttpPost;
  const factory FerrostarRouteRequest.httpGet({
    required String url,
    required Map<String, String> headers,
  }) = FerrostarRouteRequest_HttpGet;
}
